version: "3.9"
services:
  server:
    build:
      context: .
    depends_on:
      - "mysql"
    ports:
      - "1354:1354/tcp"
    secrets:
      - db_password
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql-docker-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: game
      MYSQL_USER: gameserver
      MYSQL_PASSWORD: bestToDoItSimple
secrets:
  db_password:
    file: db_passwd.txt