version: "3.9"
services:
  server:
    image: yutytuty/cyber_server:latest
    depends_on:
      - "mysql"
    ports:
      - "1354:1354/tcp"
  mysql:
    image: yutytuty/cyber_mysql:latest
    container_name: mysql-docker-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: game
      MYSQL_USER: gameserver
      MYSQL_PASSWORD: bestToDoItSimple