version: "3.9"
services:
  server:
    build:
      context: .
    depends_on:
      - "db"
    ports:
      - "1354:1354/tcp"
    secrets:
      - db_password
  db:
    image: "docker.io/mysql:8"
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/mysql
    environment:
      MYSQL_DATABASE: game
      MYSQL_USER: gameserver
      MYSQL_PASSWORD: no_need_for_security
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    secrets:
      - db_password
secrets:
  db_password:
    file: db_passwd.txt
volumes:
  db_data: 

